[mypy]
warn_return_any = False
warn_unused_configs = False
ignore_missing_imports = True
no_implicit_optional = False
warn_redundant_casts = False
warn_unused_ignores = False
warn_unreachable = False

[mypy-src.*]
follow_imports = silent

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True
